spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/postgres
    username: ######
    password: ######
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8085
